[package]
name = "snuffi"
version = "0.0.1"
publish = false

[dependencies]
rocket = { version = "0.4.5", features = ["tls"] }
rocket_contrib = { version = "0.4.5", features = ["json"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
