# The certificate/private key pair used here was generated via openssl using the
# `gen_cert.sh` script located in the `private/` subdirectory.
#
# The certificate is self-signed. As such, you will need to trust it directly
# for your browser to refer to the connection as secure. You should NEVER use
# this certificate/key pair. It is here for DEMONSTRATION PURPOSES ONLY.
[global.tls]
certs = "private/cert.pem"
key = "private/key.pem"

[development]
address = "localhost"
port = 8000
log = "normal"
limits = { forms = 32768, json = 128 }

[staging]
address = "0.0.0.0"
port = 8000
log = "normal"
limits = { forms = 32768, json = 128  }

[production]
address = "0.0.0.0"
# address = "snuf.fi"
port = 80
log = "critical"
limits = { forms = 32768, json = 128 }